# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/test_clk1/Arty-Z7-20-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_10M_0/design_1_rst_ps7_0_10M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_10M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_10M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_paralell2axi_0_0/design_1_paralell2axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_paralell2axi_0_0 || ORIG_REF_NAME==design_1_paralell2axi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_1/design_1_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_1 || ORIG_REF_NAME==design_1_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_2/design_1_axis_data_fifo_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_2 || ORIG_REF_NAME==design_1_axis_data_fifo_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mapper_0_0/design_1_mapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mapper_0_0 || ORIG_REF_NAME==design_1_mapper_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
